import{a as w,S as v,i}from"./assets/vendor-CrlV4O_2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",S="50283809-fb8098277938dfac7f33d4612";async function f(r,o){const e={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await w.get(q,{params:e})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".load-more"),h=document.querySelector(".loader"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(e=>`<li class="gallery-item">
    <a href="${e.largeImageURL}">
    <img src="${e.webformatURL}" alt="${e.tags}" />
    </a>
    <div class="gallery-info">
    <p><b>Likes:</b> ${e.likes}</p>
    <p><b>Views:</b> ${e.views}</p>
    <p><b>Comments:</b> ${e.comments}</p>
    <p><b>Downloads:</b> ${e.downloads}</p>
    </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",o),R.refresh()}function B(){m.innerHTML=""}function g(){h.classList.add("is-visible")}function b(){h.classList.remove("is-visible")}function L(){p.classList.remove("hidden")}function a(r){p.classList.add("hidden")}const u=document.querySelector(".form"),P=document.querySelector(".load-more");let $="",n=1,d=0;u.addEventListener("submit",async r=>{r.preventDefault();const o=u.elements["search-text"].value.trim();if(n=1,B(),a(),!o){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}try{g();const e=await f(o,n);if(d=e.totalHits,e.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"white",position:"topRight",icon:" ",iconText:"✗",iconColor:"white"});return}y(e.hits),d>n*15?L():(a(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"An error occurred. Please try again later.",position:"topRight"})}finally{b()}});P.addEventListener("click",async()=>{n+=1;try{a(),g();const r=await f($,n);y(r.hits),n*15>=d?(a(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L(),E()}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{b()}});function E(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
