import{a as v,S,i}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const q="https://pixabay.com/api/",R="50283809-fb8098277938dfac7f33d4612";async function m(o,t){const r={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await v.get(q,{params:r})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".load-more"),y=document.querySelector(".loader"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(r=>`<li class="gallery-item">
    <a href="${r.largeImageURL}">
    <img src="${r.webformatURL}" alt="${r.tags}" />
    </a>
    <div class="gallery-info">
    <p><b>Likes:</b> ${r.likes}</p>
    <p><b>Views:</b> ${r.views}</p>
    <p><b>Comments:</b> ${r.comments}</p>
    <p><b>Downloads:</b> ${r.downloads}</p>
    </div>
    </li>`).join("");p.insertAdjacentHTML("beforeend",t),B.refresh()}function P(){p.innerHTML=""}function b(){y.classList.add("is-visible")}function L(){y.classList.remove("is-visible")}function w(){h.classList.remove("hidden")}function l(o){h.classList.add("hidden")}const f=document.querySelector(".form"),$=document.querySelector(".load-more");let a="",n=1,u=0;f.addEventListener("submit",async o=>{if(o.preventDefault(),a=f.elements["search-text"].value.trim(),n=1,P(),l(),!a){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}try{b();const t=await m(a,n);if(u=t.totalHits,t.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"white",position:"topRight",icon:" ",iconText:"✗",iconColor:"white"});return}g(t.hits),u>n*15?w():(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"An error occurred. Please try again later.",position:"topRight"})}finally{L()}});$.addEventListener("click",async()=>{n+=1;try{l(),b();const o=await m(a,n);g(o.hits),n*15>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(),E()}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{L()}});function E(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
